"""add job groups

Revision ID: 51c00480b6f8
Revises: f83243312b19
Create Date: 2026-08-29 20:02:40.381631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c00480b6f8'
down_revision: Union[str, Sequence[str], None] = 'f83243312b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('company_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', 'company_code', name='uq_job_groups_normalized_name_company_code')
    )
    op.create_index(op.f('ix_job_groups_company_code'), 'job_groups', ['company_code'], unique=False)
    op.create_index(op.f('ix_job_groups_normalized_name'), 'job_groups', ['normalized_name'], unique=False)
    op.add_column('jobs', sa.Column('job_group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_job_group_id'), 'jobs', ['job_group_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'job_groups', ['job_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_job_group_id'), table_name='jobs')
    op.drop_column('jobs', 'job_group_id')
    op.drop_index(op.f('ix_job_groups_normalized_name'), table_name='job_groups')
    op.drop_index(op.f('ix_job_groups_company_code'), table_name='job_groups')
    op.drop_table('job_groups')
    # ### end Alembic commands ###
