"""add raw_content_hash to jobs

Revision ID: 8cbcd537e965
Revises: fbc06ee08afc
Create Date: 2026-08-21 17:02:53.966750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbcd537e965'
down_revision: Union[str, Sequence[str], None] = 'fbc06ee08afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('raw_content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_raw_content_hash'), 'jobs', ['raw_content_hash'], unique=False)
    op.create_unique_constraint('uq_jobs_raw_content_hash', 'jobs', ['raw_content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_raw_content_hash', 'jobs', type_='unique')
    op.drop_index(op.f('ix_jobs_raw_content_hash'), table_name='jobs')
    op.drop_column('jobs', 'raw_content_hash')
    # ### end Alembic commands ###
