"""create initial database tables

Revision ID: d6d5f3da0a69
Revises: 
Create Date: 2026-08-20 01:32:48.013959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6d5f3da0a69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_code', sa.String(length=64), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('reports_to', sa.String(length=255), nullable=True),
    sa.Column('number_of_job_holders', sa.Integer(), nullable=True),
    sa.Column('number_of_direct_reports', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_industry', sa.String(length=255), nullable=True),
    sa.Column('input_type', sa.String(length=32), nullable=True),
    sa.Column('original_file_name', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('job_purpose', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('record_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_jobs_job_code'), 'jobs', ['job_code'], unique=False)
    op.create_index(op.f('ix_jobs_job_title'), 'jobs', ['job_title'], unique=False)
    op.create_table('job_additional_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'key', name='uq_job_additional_info_job_key')
    )
    op.create_index(op.f('ix_job_additional_information_key'), 'job_additional_information', ['key'], unique=False)
    op.create_table('job_comparisons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('new_job_id', sa.String(length=64), nullable=False),
    sa.Column('job_code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reference_jobs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['new_job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_comparisons_job_code', 'job_comparisons', ['job_code'], unique=False)
    op.create_index('ix_job_comparisons_new_job_id', 'job_comparisons', ['new_job_id'], unique=False)
    op.create_index(op.f('ix_job_comparisons_status'), 'job_comparisons', ['status'], unique=False)
    op.create_table('job_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirements_category'), 'job_requirements', ['category'], unique=False)
    op.create_index('ix_job_requirements_job_id_category', 'job_requirements', ['job_id', 'category'], unique=False)
    op.create_table('job_responsibilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_responsibilities_job_id_position', 'job_responsibilities', ['job_id', 'position'], unique=False)
    op.create_table('job_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('job_code', sa.String(length=64), nullable=True),
    sa.Column('comparison_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_substantive_role_change', sa.Boolean(), nullable=True),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['job_comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_reports_job_code'), 'job_reports', ['job_code'], unique=False)
    op.create_index('ix_job_reports_job_id', 'job_reports', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_reports_status'), 'job_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_reports_status'), table_name='job_reports')
    op.drop_index('ix_job_reports_job_id', table_name='job_reports')
    op.drop_index(op.f('ix_job_reports_job_code'), table_name='job_reports')
    op.drop_table('job_reports')
    op.drop_index('ix_job_responsibilities_job_id_position', table_name='job_responsibilities')
    op.drop_table('job_responsibilities')
    op.drop_index('ix_job_requirements_job_id_category', table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_category'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_job_comparisons_status'), table_name='job_comparisons')
    op.drop_index('ix_job_comparisons_new_job_id', table_name='job_comparisons')
    op.drop_index('ix_job_comparisons_job_code', table_name='job_comparisons')
    op.drop_table('job_comparisons')
    op.drop_index(op.f('ix_job_additional_information_key'), table_name='job_additional_information')
    op.drop_table('job_additional_information')
    op.drop_index(op.f('ix_jobs_job_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_code'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_name'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
