"""add company_code to jobs

Revision ID: f83243312b19
Revises: 8cbcd537e965
Create Date: 2026-08-29 15:58:47.846423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83243312b19'
down_revision: Union[str, Sequence[str], None] = '8cbcd537e965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('company_code', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_company_code'), 'jobs', ['company_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_company_code'), table_name='jobs')
    op.drop_column('jobs', 'company_code')
    # ### end Alembic commands ###
