"""add content_hash to jobs

Revision ID: fbc06ee08afc
Revises: d6d5f3da0a69
Create Date: 2026-08-21 16:23:08.716833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc06ee08afc'
down_revision: Union[str, Sequence[str], None] = 'd6d5f3da0a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_content_hash'), 'jobs', ['content_hash'], unique=False)
    op.create_unique_constraint('uq_jobs_content_hash', 'jobs', ['content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_content_hash', 'jobs', type_='unique')
    op.drop_index(op.f('ix_jobs_content_hash'), table_name='jobs')
    op.drop_column('jobs', 'content_hash')
    # ### end Alembic commands ###
